name             'sitecore8-installer'
maintainer       'Corey McClelland'
maintainer_email 'corey@agilereaction.io'
license          'Apache 2.0'
description      'Configures a windows vm for sitecore 8'
version          '1.0.0'
depends          'chocolatey'
depends          'windows'
depends          'minitest-handler'
depends          'chocolatey-installer'
supports         'windows'
